Remove the need for an initial page view.
segment-integrations/analytics.js-integration-chameleon pull request #8
Opened 2017-06-07 18:59 UTC by bnorton

2017-06-07 19:35 UTC, bnorton commented
Note: I am pulling in upstream changes (from another integration) specifically around 'modernizing the test harness' commits in other repos.

2017-06-07 20:02 UTC, bnorton commented
@ndhoule + @ Peripheral1994 This is ready to go! It includes small updates to not `assumePageview` and to not pass through an `anonymousId` as if it were the real `userId`

Thanks for having a look!

p.s. If there is someone else to loop in can you tag them here?

2017-06-07 20:03 UTC, bnorton commented
@ndhoule + @Peripheral1994 This is ready to go! It includes small updates to not assumePageview and to not pass through an anonymousId as if it were the real userId

Thanks for having a look!

p.s. If there is someone else to loop in can you tag them here?

2017-06-12 22:27 UTC, bnorton commented
Bump to @sperand-io @hankim813 @stevenmiller888 anything else needed here?

2017-06-12 23:00 UTC, hankim813 requested changes
sorry for the delay @bnorton but some comments to resolve! thanks!

2017-06-12 23:00 UTC, hankim813 commented on lib/index.js
> +  var uid = options.id || identify.userId() || null;
we can probably just do:

```
var traits = identify.traits();
// remove duplicate id
delete traits.id;

window.chmln.identify(identify.userId(), traits);
```

2017-06-12 23:00 UTC, hankim813 commented on lib/index.js
> +  var uid = options.id || identify.userId() || null;
and note that `userId()` can return `undefined` for anonymous users

2017-06-12 23:00 UTC, hankim813 commented on lib/index.js
> -Chameleon.prototype.group = function(group) {
any reason why we are removing this? this will be a breaking change

2017-06-12 23:00 UTC, hankim813 commented on lib/index.js
> -Chameleon.prototype.alias = function(alias) {
same here

2017-06-13 01:38 UTC, bnorton commented on lib/index.js
> -Chameleon.prototype.group = function(group) {
@hankim813 Those functions were no-ops on the backend for us -- I'll add them back with similar implementation on the frontend.

2017-06-13 18:21 UTC, bnorton commented
@hankim813 the requested changes are in! -- thanks

2017-06-13 19:55 UTC, hankim813 requested changes
lgtm, small nitpick. 

can you also add a release commit on top of this?

bump `package.json` version ... probably a patch? I'm interpreting this is mainly a bug fix + refactor?

then update `HISTORY.md` with convention
`$ git commit -m 'Release x.x.x'`

2017-06-13 19:55 UTC, hankim813 commented on lib/index.js
> +  traits.uid = group.groupId();
ahh if you need to alias, we can write this entire function like this:

```
window.chmln.set({ company: group.traits({ id: 'uid' }) });
```

2017-06-14 18:49 UTC, hankim813 commented
@bnorton ahh so close! you forgot to bump the `version` in `package.json` to `2.0.1`!

2017-06-14 18:54 UTC, bnorton commented
@hankim813 yikes you're right -- I force pushed to cover my mistake :)

2017-06-14 20:53 UTC, hankim813 approved these changes

2017-06-14 20:54 UTC, merged

2017-06-14 21:56 UTC, hankim813 commented
@bnorton deployed! might want to wait 10 min or so for cache to clear